language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.3
  - 1.6.1
otp_release:
  - 18.3
  - 19.3
  - 20.0
  - 20.1
matrix:
  exclude:
    - otp_release: 18.3
      elixir: 1.6.1
    - otp_release: 20.0
      elixir: 1.3.4
    - otp_release: 20.1
      elixir: 1.3.4
notifications:
  recipients:
    - andrew@andrewtimberlake.com
